$(document).ready(function () {

	// =====================Problem input box ===================
	// this section defines the input box and its bahaviour when 
	// writing to it.

	$('.problem-title').click(function(){
		$('.problem-detail').show();
	});

	

	$('.problem-detail').autosize();



	//When the done button is clicked a new item is added. down the road I 
	//Would like this information to be generated by the server rather than PHP.

	// Jquery actions that define how the form is submitted

	$('.problem-submit').click(function(e) {
				e.preventDefault();
			// jQuery's .text() method is used here to escape input from input.problem-title();
			if ($('.problem-title').val() == "" && $('.problem-detail').val() == "") {
	
				$('.problem-title').val("");
				$('.problem-detail').val("");
				$('.problem-detail').height("20px");
				$('.problem-detail').css("display","none");
				return false;
			} else {
				$('.saved-note').prepend("<div class='col-xs-12 col-sm-6 col-md-4 col-lg-4'>"
				+"<div class='note-wrapper'>"
				+"<div class='note-title'><strong> </strong></div>" //Title is generated here
				+"<div class='note-detail'><pre> detail</pre></div>" //not details are generated here
				+"<div class='note-options'> Color | Archive | Option3 </div>"
				+"</div>"
				+"</div>");

				$('.saved-note > div:first-child > .note-wrapper > .note-detail').text($('.problem-detail').val());
				$('.saved-note > div:first-child > .note-wrapper > .note-title strong').text($('.problem-title').val());

				$('.problem-title').val("");
				$('.problem-detail').val("");
				$('.problem-detail').height("20px");
				$('.problem-detail').css("display","none");
				return false;
			}
				
			// escape input end
		});

	// $('').click(function(){
	// 		if (($('.problem-title').val() == "") && ($('problem-detail').val() == "")) {
	
	// 		} else {
	// 			$('.saved-note > div:first-child > .note-wrapper > .note-detail').text($('.problem-detail').val());
	// 			$('.saved-note > div:first-child > .note-wrapper > .note-title strong').text($('.problem-detail').val());
	// 			$('.problem-title').val("");
	// 			$('.problem-detail').val("");
	// 			$('.problem-detail').css("display","none");
	// 		}
	// 	});


	// Submit Behaviour end


	// ================Problem input box end===================

}); //=========== End of Document.ready ==========