$(document).ready(function () {

	/* Ajax Test */
$(".problem-submit").click(function(){




});
	
	/* Ajax tests end */

	

	// =====================Problem input box ===================
	// this section defines the input box and its bahaviour when 
	// writing to it.

	$('.problem-title').click(function(){
		$('.problem-detail').show();
		$('.problem-options').show();
	});

	$('.problem-title').focus(function(){
		$('.problem-detail').show();
		$('.problem-options').show();
	});




	/* Jquery plugin that autosizes textareas (thanks github) */
	$('.problem-detail').autosize();


	
	/*  
		.problem-submit.click()
		- When the done button is clicked the item will be added to the body of the page
		- If nothing is entered, nothing will be added to the body
		- Input is escapted using jquerys $.text() method.

		//Would like this information to be generated by PHP rather than JS.
		*/
		$('.problem-submit').click(function(e) {
			e.preventDefault();
			// jQuery's .text() method is used here to escape input from input.problem-title();
			if ($('.problem-title').val() == "" && $('.problem-detail').val() == "") {
				
				// Clear Contents
				$('.problem-title').val("");
				$('.problem-detail').val("");
				$('.problem-detail').height("20px");
				$('.problem-detail').css("display","none");
				$('.problem-options').css("display","none");
				return false;

				//DON'T RUN AJAX REQUEST TO PROCESSOR PAGE

			} else {

// =============== ajax start =================

			var problem_detail = $('.problem-detail').val();
var problem_title = $('.problem-title').val();
	

	var xhr = new XMLHttpRequest();

	xhr.onreadystatechange=function() {
		if (xhr.status === 200) {
			document.getElementById("status-container").innerHTML = xhr.responseText;
		}
	}
	xhr.open("POST", "resources/config.php", true);
	xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xhr.send("title="+problem_title+"&detail="+problem_detail+"");
	/* ============== AJAX END ================ */


				$('.saved-note').prepend("<div class='col-xs-12 col-sm-6 col-md-4 col-lg-4 note-container'>"
					+"<div class='note-wrapper'>"
				+"<div class='note-title'><strong> </strong></div>" //Title is generated here
				+"<div class='note-detail'><pre> detail</pre></div>" //not details are generated here
				+"<div class='note-options'> Color | Archive | Option3 </div>"
				+"</div>"
				+"</div>");

				// Escape Input
				$('.saved-note > div:first-child > .note-wrapper > .note-detail').text($('.problem-detail').val());
				$('.saved-note > div:first-child > .note-wrapper > .note-title strong').text($('.problem-title').val());

				// Clear Contents
				$('.problem-title').val("");
				$('.problem-detail').val("");
				$('.problem-detail').height("20px");
				$('.problem-detail').css("display","none");
				$('.problem-options').css("display","none");


				//Porblem. Trying to make it so that when you hover ove a box, the option box appears.
				$('.note-container').hover(function(){
					$(".note-options",this).css("visibility","visible");
					return false;
				},function(){
					$(".note-options",this).css("visibility","hidden");
					return false;
				});
					
				


				//RUN AJAX REQUEST TO PROCESSOR PAGE.
			}
			

			
		});

// When the user clicks ousite of the input or area. it closes.
//	- Make proximity larger down the line.

$("body:not(input)").click(function(e){

	if($(e.target).is(':not(.problem-title, .problem-detail)')) {

		if ($('.problem-title').val() == "" && $('.problem-detail').val() == "") {

				// Clear Contents
				$('.problem-title').val("");
				$('.problem-detail').val("");
				$('.problem-detail').height("20px");
				$('.problem-detail').css("display","none");
				$('.problem-options').css("display","none");
				

				//DON'T RUN AJAX REQUEST TO PROCESSOR PAGE

			} else {
				$('.saved-note').prepend("<div class='col-xs-12 col-sm-6 col-md-4 col-lg-4 note-container'>"
					+"<div class='note-wrapper'>"
				+"<div class='note-title'><strong> </strong></div>" //Title is generated here
				+"<div class='note-detail'><pre> detail</pre></div>" //not details are generated here
				+"<div class='note-options'> Color | Archive | Option3 </div>"
				+"</div>"
				+"</div>");

				// Escape Input
				$('.saved-note > div:first-child > .note-wrapper > .note-detail').text($('.problem-detail').val());
				$('.saved-note > div:first-child > .note-wrapper > .note-title strong').text($('.problem-title').val());

				// Clear Contents
				$('.problem-title').val("");
				$('.problem-detail').val("");
				$('.problem-detail').height("20px");
				$('.problem-detail').css("display","none");
				$('.problem-options').css("display","none");
				

				//RUN AJAX REQUEST TO PROCESSOR PAGE
			}

		}

	});


	

}); //=========== End of Document.ready ==========