<?php
// Get note.php will serve these functions:
// - Retreives all notes stored in database
// - Stores each value into an array
// - The html is generated by PHP and possably uses javascript to append to the main body

//For now I will make it so that if there is a failure. The information will not show


include("config.php");


try {
	$query = "SELECT * FROM tbl_notes";
	$stmt = $db->prepare($query);
	$results = $stmt->execute();

} catch (exception $e) {
	echo "There was a problem connecting to the database";
	exit;

}

$results_array = $stmt->fetchAll(PDO::FETCH_ASSOC);	

foreach ($results_array as $value) {
	foreach ($value as $v) {
		echo $v['user_id'] . "<br />";
	}
}


var_dump($results_array);
?>