<?php
// Get note.php will serve these functions:
// - Retreives all notes stored in database
// - Stores each value into an array
// - The html is generated by PHP and possably uses javascript to append to the main body

//For now I will make it so that if there is a failure. The information will not show


include("config.php");


try {
	$query = "SELECT * FROM tbl_notes";
	$stmt = $db->prepare($query);
	$results = $stmt->execute();

} catch (exception $e) {
	echo "There was a problem connecting to the database";
	exit;

}

$results_array = $stmt->fetchAll(PDO::FETCH_ASSOC);	

foreach ($results_array as $value) {


echo "<div id='". $value['note_id'] . "' class='col-xs-12 col-sm-6 col-md-4 col-lg-4 note-container'>";
echo "<div class='note-wrapper'>";
echo "<div class='note-title'><strong>".$value['title']."</strong></div>";
echo "<div class='note-detail'>".$value['details']."</div>";
echo "<div class='note-options'> Color | Archive | <button class='delete-note'> Delete </button> </div>";
echo "</div>";
echo "</div>";				
}
?>